### ISSUE TITLE
More install notes

### ISSUE THREAD

**Issue by yrnkrn** [vaibhavk97/GoBooDo#1]
Worth mentioning that python3 is required and that PIL resides in Pillow, so

    pip3 install requests bs4 Pillow fpdf

should install all dependencies.

**Comment by yrnkrn** [comment]
html5lib is also a dependency, so

    pip3 install requests bs4 Pillow fpdf html5lib

**Comment by vaibhavk97** [comment]
The install notes have been updated, thanks for notifying.
