### ISSUE TITLE
Any way to run multiple IDs at once?

### ISSUE THREAD

**Issue by uraniumcores** [vaibhavk97/GoBooDo#10]
I was able to crawl several Google Books magazine runs and have a list of every ID, so is there any way to put them all into GoBooDo at once? I tried entering them in the settings.json as "id" : [ "EXAMPLE" , "EXAMPLE", "EXAMPLE" ] and changing the GoBooDo.py to pull the ID from settings but it did not work. I also tried entering the list in the command --id=EXAMPLE, EXAMPLE, EXAMPLE. Thanks

**Comment by bhamshu** [comment]
for now, you can open multiple terminals - one for each id. it works for me
