### ISSUE TITLE
Issue in downloading previews, probably proxies

### ISSUE THREAD

**Issue by Theroumag** [vaibhavk97/GoBooDo#11]
In downloading ``--id=l3GD2EgazCkC`` pages have stopped being fetched with ``Could not fetch link for page PAxxx``. Tried trying serval different proxies and changing my ip. Running program through cmd with admin account and the fetched pages result in
```python
------------------- Fetching Images -------------------
[WinError 5] Access is denied
[WinError 5] Access is denied
[WinError 5] Access is denied
.
.
.
[WinError 5] Access is denied
```

**Comment by vaibhavk97** [comment]
I am unable to replicate this issue, can you list the steps that you take.
