### ISSUE TITLE
cannot identify image file <_io.BytesIO object at ...>

### ISSUE THREAD

**Issue by xaviermchot** [vaibhavk97/GoBooDo#14]
Many downloads of image files end like this. Why?
Thanks

**Comment by vaibhavk97** [comment]
Can you please provide the link of the book for which this error results.

**Comment by xaviermchot** [comment]
This happened with any books. But I think it's due to the proxy I was using. Without proxy it is working; or better to say, it is not fetching the images because they are probably unavailable.
Thanks
