### ISSUE TITLE
Settings.json Error

### ISSUE THREAD

**Issue by LonelyDavid** [vaibhavk97/GoBooDo#16]
Error info
GoBooDo.py, line 25, in <Module> "with open('settings.json') as ofile:"
FileNofoundError: [Errno 2] No Such File or Directory: 'settings.json'

**Comment by vaibhavk97** [comment]
Can you please check if you have downloaded the entire repository.

**Comment by craziecaesium** [comment]
I encountered the same error, and I have downloaded the entire repository.

I found a workaround solution by setting the absolute path (e.g. I placed the folder on Desktop):

line 25: with open('settings.json') as ofile:

change to
with open(r'C:\users\_yourname_\Desktop\GoBooDo-master\settings.json') as ofile:

and also

line 45: with open('proxies.txt','r') as ofile:

change to
with open(r'C:\users\_yourname_\Desktop\GoBooDo-master\proxies.txt','r') as ofile:
