### ISSUE TITLE
Received invalid response

### ISSUE THREAD

**Issue by Fighteros** [vaibhavk97/GoBooDo#24]
how to solve this problem

**Comment by vaibhavk97** [comment]
Can you please share the exact message along with the ID of the book that you were fetching.

**Comment by Fighteros** [comment]
ould not fetch link for page PA202
Could not fetch link for page PA203
Could not fetch link for page PA204
Could not fetch link for page PA205
Could not fetch link for page PA206
Could not fetch link for page PA207
Could not fetch link for page PA208
Could not fetch link for page PA209
Could not fetch link for page PA210
Could not fetch link for page PA212
Could not fetch link for page PA213
Could not fetch link for page PA215
Could not fetch link for page PA217
Could not fetch link for page PA218
Could not fetch link for page PA219
Could not fetch link for page PA220
Could not fetch link for page PA221
Could not fetch link for page PA222
Could not fetch link for page PA223
Could not fetch link for page PA224
Could not fetch link for page PA225
Could not fetch link for page PA226
Could not fetch link for page PA227
Could not fetch link for page PA230
Could not fetch link for page PA231
Could not fetch link for page PA232
Could not fetch link for page PA233

**Comment by Fighteros** [comment]
GoBooDo.py --id nOJUCgAAQBAJ&printsec=frontcover&source

**Comment by felipeacsi** [comment]
You need to delete everything after `&` (including `&`).

The messages you are receiving are normal. Try again to download pages that couldn't be fetched.

**Comment by UnlimitedChild** [comment]
PS U:\GoBooDo> py GoBooDo.py --id=ARUIlwYhQpAC

 .88888.            888888ba                    888888ba
d8'   `88           88    `8b                   88    `8b
88        .d8888b. a88aaaa8P' .d8888b. .d8888b. 88     88 .d8888b.
88   YP88 88'  `88  88   `8b. 88'  `88 88'  `88 88     88 88'  `88
Y8.   .88 88.  .88  88    .88 88.  .88 88.  .88 88    .8P 88.  .88
 `88888'  `88888P'  88888888P `88888P' `88888P' 8888888P  `88888P'
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                     

Received invalid response
PS U:\GoBooDo>

**Comment by KnightOfSPUD** [comment]
It seems to stop downloading after a certain threshold

**Comment by pixardora** [comment]
Hello I came across the same problem: 
GoBooDo.py --id=LEQjEAAAQBAJ
Received invalid response
Do you know how to solve it? Thank you.
