### ISSUE TITLE
proxy not working

### ISSUE THREAD

**Issue by Jorzef** [vaibhavk97/GoBooDo#25]
Hello i've configured the script with .json file to use proxies and it is not working it returns a could not fetch a link for a lot of pages, i've tried to change the ip's on the list that came with your release but with no success , any ideas?

**Comment by vaibhavk97** [comment]
This only to do with the qualities of proxies that you are using. High-quality proxies give a good return in terms of the number of pages fetched. Therefore, I would suggest you use premium proxies. If that is not the case, you need to increase the waits between the subsequent cycles of page fetching.
