### ISSUE TITLE
No "requests"

### ISSUE THREAD

**Issue by KnightOfSPUD** [vaibhavk97/GoBooDo#26]
Traceback (most recent call last):
  File "GoBooDo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Kishanjvaghela** [comment]
Try `sudo pip3 install requests`

**Comment by Kishanjvaghela** [comment]
Check https://github.com/vaibhavk97/GoBooDo#dependencies

**Comment by KnightOfSPUD** [comment]
ERROR: Could not find a version that satisfies the requirement requirements.txt
(from versions: none)
ERROR: No matching distribution found for requirements.txt

**Comment by KnightOfSPUD** [comment]
It's okay, I had to install the dependencies one by one

**Comment by Kishanjvaghela** [comment]
> It's okay, I had to install the dependencies one by one

You close this issue, if resolved
