### ISSUE TITLE
Using Tesseract in Linux?

### ISSUE THREAD

**Issue by GrahamboJangles** [vaibhavk97/GoBooDo#29]
The settings.json seems like it only supports using Tesseract with a path that leads to an .exe file. Is there a way to run this in Linux with Tesseract? If not, is there a way to run this without Tesseract in Linux?

**Comment by vaibhavk97** [comment]
The path is only used if tesseract is not accessible via environment variables. Consider the following comment from the config file.
  _`"tesseract_path": 'C:\program Files\Tesseract-OCR\tesseract.exe', // The path for tesseract engine if not available via environment variables.`_

**Comment by GrahamboJangles** [comment]
I'd like to know @maferv 's question as well @vaibhavk97

**Comment by sfolje0** [comment]
> 
> 
> What would the environmental path needed to activate tesseract on GNU/Linux?
> I already pointed to the correct binary in the config file (/usr/bin/tesseract) but I'm getting no OCR in the result pdf.
> Also, it would be important to have an option to determine the appropriate language(s) for each book, so that the OCR would pick out the words correctly.

Hi @maferv and @GrahamboJangles,
I tried exactly what you did (/usr/bin/tesseract) after of course installing tesseract (apt install teseract-ocr on Ubuntu (WSL). And It worked perfectly fine for me!
I also replied in this [issue](https://github.com/vaibhavk97/GoBooDo/issues/32#issuecomment-783994404_).
