### ISSUE TITLE
Is it possible to run on a mac instead of pc?, if so how can you advise on setting up tesseract for MacOS 11.2.2

### ISSUE THREAD

**Issue by DIGITALGEEZER** [vaibhavk97/GoBooDo#40]

**Comment by leonardovida** [comment]
@DIGITALGEEZER Tesseract is working on my side (MacOS 11.2.2) by installing tesseract using brew:
`brew install tesseract`
If you want to recognize more languages install using the `-lang` option:
`brew install tesseract-lang`
