### ISSUE TITLE
Filter out bad images

### ISSUE THREAD

**Issue by 2sls** [vaibhavk97/GoBooDo#5]
Google will offer blank image pages for download that the script is not currently able to filter out.
On a test example with 26 pages downloaded, 6 were "images not found"
Here's the image not found picture:
https://imgur.com/a/s4tp37V

Maybe provide users with some options on how to filter:
1. the checksum of the image is probably identical so you could filter based on that.
2. use some ocr package like tessercat to pull the image content and filter based on that
3. take some pre-trained image similarity model and get a score of the image relative to the baseline "image not found" picture.

**Comment by vaibhavk97** [comment]
Tesseract support is now added.
