### ISSUE TITLE
no book id given or incorrect book id given when the id is correct

### ISSUE THREAD

**Issue by IvanYanovskiy** [vaibhavk97/GoBooDo#50]
Hey, I am very new to running python scripts. I think I figured it out, but when I type "goboodo.py -id=lK5fAAAAcAAJ" it says "no book id given or incorrect book id given when the id is correct" while the id is definitely correct. What might cause that?

**Comment by vaibhavk97** [comment]
Use
`python GoBooDo.py --id=lK5fAAAAcAAJ
`or
`python3 GoBooDo.py --id=lK5fAAAAcAAJ
`
depending on your version of python

**Comment by IvanYanovskiy** [comment]
Thanks, that helped
