### ISSUE TITLE
syntax error in GoBooDo.py line 82

### ISSUE THREAD

**Issue by jalamurti** [vaibhavk97/GoBooDo#56]
python GoBooDo.py --id=RDQEBACHjokC
  File "GoBooDo.py", line 82
    print(f'Downloading {self.name[:-15]}')
                                         ^
SyntaxError: invalid syntax

**Comment by minamotorin** [comment]
You seem use python2. But this program requires python3: `python3 GoBooDo.py --id=RDQEBACHjokC`
