### ISSUE TITLE
Can it be made to work with magazines?

### ISSUE THREAD

**Issue by uraniumcores** [vaibhavk97/GoBooDo#6]
I've tried this with several of the [open magazines](https://books.google.com/books/about/LIFE.html?id=R1cEAAAAMBAJ) on Google Books that display every page but none worked. The open magazines would not need a proxy because every page is available to everyone. Is there any way to use this without proxies? I tried just leaving the proxies.txt empty and it still didn't work. 
![goboodo](https://user-images.githubusercontent.com/61292994/74975318-e22dcf00-53f4-11ea-8cd0-69a79bb137ef.JPG)

**Comment by vaibhavk97** [comment]
The changes have been made. Thanks for notifying.

**Comment by uraniumcores** [comment]
Thank you so much! It works perfectly, I am amazed by how high quality the images are!
