### ISSUE TITLE
obstinate_pages builds up repeated sets of same missing links

### ISSUE THREAD

**Issue by L0que** [vaibhavk97/GoBooDo#7]
Running the script a large number of times for one book seems to result in repetition in the obstinate_pages (meaning the same group of obstinate links is repeated over and over and over).  I'm not sure if this is expected behavior.  

[obstinate_pages.zip](https://github.com/vaibhavk97/GoBooDo/files/4240732/obstinate_pages.zip)

**Comment by vaibhavk97** [comment]
Noted, the issue has been fixed.
