### ISSUE TITLE
Suggestion: manually enter known missing page numbers not found in obstinate_pages

### ISSUE THREAD

**Issue by L0que** [vaibhavk97/GoBooDo#8]
I have had great results with the script, including in some cases 'completing' the download of all page links and all page images.  However, sometimes there are still missing pages in the book and these pages are not listed in obstinate_pages.  If I delete the folder and re-try, multiple times even, it always misses the same set of pages so it never tries to get their page links.

If it were possible to manually enter the known missing 10 pages or whatever to obstinate_pages, wouldn't the script start trying to obtain those page links?  I attempted in notepad++ to add pages to obstinate_pages mimicking the formatting of that file the best I could, but it was obviously not correct, since the script would not proceed after the edits.

If there were an option to create a text file (e.g. really_obstinate_pages) listing pages:  PA07, PT123, PT207 that the script would add, that would be great.  Otherwise if you could possibly advise how to insert a few pages within obstinate_pages without breaking the script, that would work too.  Thanks so much.

**Comment by vaibhavk97** [comment]
I think the problem that you are referring to here is that there are some pages for which there is no entry in the obstinate pages list. So what happens is that, Google populates an initial list for those pages for which it is willing to share the links and pages. The pages for which there is no entry, we can't do anything about them. You have to look to other places to get those pages.

**Comment by L0que** [comment]
That could be right and maybe there is nothing that can be done.  

To be more precise, I just wondered if after GoBooDo completes everything, but there is say two pages missing (PT120 and PT180) that Google Books might *eventually* make those page links for PT120 and PT180 available even though the links and images are not yet available.  If so, it would make sense to have a way to try fetching those 'known' missing pages.

Either way thanks for the great work you are doing!
