### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by gitrcvrd** [vaibhavk97/GoBooDo#83]
I'm getting this message:

**"name='__Secure-ENID', domain=None, path=None"
Received invalid response**

I tried to follow the forum but the fixes seem to be arealdy applied to the code.
Tesseract is installed and settings are configured.

**Comment by GhassanAlKaraan** [comment]
so how did you solve this issue?

**Comment by gitrcvrd** [comment]
The issue was caused by the script not setting the required __Secure-ENID cookie for Google requests. To fix it, I added a resethead() function that sends a request to Google, retrieves the __Secure-ENID cookie, and includes it in the headers for all subsequent requests. This ensures that Google recognizes the requests and processes them correctly.

```
def resethead(self):
    try:
        req = requests.get("https://google." + self.country, cookies={'CONSENT': 'YES+1'}, verify=False)
        secure_enid_cookie = req.cookies.get('__Secure-ENID', 'default_value')
        self.head = {
            'Host': 'books.google.' + self.country,
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.00',
            'Accept': '*/*',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'close',
            'Cookie': "__Secure-ENID=" + secure_enid_cookie,
        }
    except Exception as e:
        print(f"An error occurred: {e}")
```
